name: Deploy Lambda Function and Upload  images to s3 bucket

on:
  workflow_dispatch:
  push:
    # Trigger the workflow for every commit to any branch
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3

      - name: Deploy Lambda function
        run: |
          zip -r lambda_function.zip lambda_function.py
          aws lambda update-function-code --function-name mylambdafunction --zip-file fileb://lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
      - name: Upload images to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
         args: --acl public-read --follow-symlinks --delete
        env:
         AWS_S3_BUCKET: mybucket19961
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'ap-south-1'
         SOURCE_DIR: 'images' 
