name: Deploy Lambda Function

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload images to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
         args: --delete
        env:
         AWS_S3_BUCKET: mybucket19961
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'ap-south-1'
         SOURCE_DIR: 'images'    

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Deploy Lambda Function
        run: |
          # Zip Lambda function code
          zip -r lambda_function.zip lambda_function.py
          if aws lambda get-function --function-name mylambdafunction --region ap-south-1 &> /dev/null; then
          echo "Lambda function already exists, skipping creation."
          else
            # Create Lambda function
           aws lambda create-function \
           --function-name mylambdafunction \
           --runtime python3.8 \
           --role arn:aws:iam::730335412815:role/lambda-s3-trigger-role \
           --handler lambda_function.lambda_handler \
           --zip-file fileb://lambda_function.zip \
           --region ap-south-1
          fi

      - name: Add S3 trigger to Lambda function
        run: |
          STATEMENT_ID=$(python3 -c 'import uuid; print(uuid.uuid4())')
          aws lambda add-permission \
            --function-name mylambdafunction \
            --statement-id STATEMENT_ID \
            --action "lambda:InvokeFunction" \
            --principal s3.amazonaws.com \
            --source-arn arn:aws:s3:::mybucket19961 \
            --region ap-south-1

          aws s3api put-bucket-notification-configuration \
            --bucket mybucket19961 \
            --notification-configuration '{
              "LambdaFunctionConfigurations": [
                {
                  "LambdaFunctionArn": "arn:aws:lambda:ap-south-1:730335412815:function:mylambdafunction",
                  "Events": [
                    "s3:ObjectCreated:*",
                    "s3:ObjectRemoved:*"
                  ],
                  "Filter": {
                    "Key": {
                      "FilterRules": [
                        {
                          "Name": "suffix",
                          "Value": ""
                        }
                      ]
                    }
                  }
                }
              ]
            }'
